### ISSUE TITLE
solr health/backup/restore scripts failing when index over 50k

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/opswx-ckan-cookbook#258]
based on harvesting a 175k store into our lowest enviornment. We have noted that solr health check/backup/replication starts to have issues and instead of continuing as normal has started to flip between main and backup instance solr.

based on https://github.com/qld-gov-au/ckanext-harvester-data-qld-geoscience/issues/19

**Comment by ThrawnCA** [comment]
Resolved by [release 5.2.10](https://github.com/qld-gov-au/opswx-ckan-cookbook/releases/tag/5.2.10).
